## Show the .npy data

In [16]:
import numpy as np

file_path = "/pc2_npy_cache/pc2_0_1724228086076331046.npy"
points = np.load(file_path)

print(f"Loaded point cloud with shape: {points.shape}")
print("First 5 points:")
print(points[:5])

Loaded point cloud with shape: (38436, 4)
First 5 points:
[[-80.778076    1.5527247 -16.137518    6.       ]
 [-80.335915    2.036607  -16.050392   10.       ]
 [-80.83289     1.5495238 -15.901518    8.       ]
 [-79.915344    2.5158896 -15.968171    8.       ]
 [-79.68988     2.997535  -15.925587    7.       ]]


In [19]:
file_path = "/data/charlie/BagMonster/Dataset/argoverse2/sensor/test/0c6e62d7-bdfa-3061-8d3d-03b13aa21f68/map/0c6e62d7-bdfa-3061-8d3d-03b13aa21f68_ground_height_surface____MIA.npy"
points = np.load(file_path)

print(f"Loaded point cloud with shape: {points.shape}")
print(points[:5])


Loaded point cloud with shape: (982, 678)
[[-24.08 -24.06 -24.06 ... -23.28 -23.27 -23.27]
 [-24.1  -24.1  -24.08 ... -23.27 -23.27 -23.25]
 [-24.1  -24.1  -24.08 ... -23.27 -23.25 -23.25]
 [-24.08 -24.08 -24.08 ... -23.25 -23.25 -23.23]
 [-24.06 -24.06 -24.06 ... -23.25 -23.25 -23.23]]


## Show the .feather data

In [22]:
import pyarrow.feather as feather

table = feather.read_table(
    "/data/charlie/BagMonster/Dataset/argoverse2/sensor/test/0c6e62d7-bdfa-3061-8d3d-03b13aa21f68/sensors/lidar/315971436059707000.feather"
)
print(table.num_rows, "rows")
print(table.schema)
print("--------------------")
for i, field in enumerate(table.schema):
    print(f"{i}: name={field.name}, type={field.type}")


100867 rows
x: halffloat
y: halffloat
z: halffloat
intensity: uint8
laser_number: uint8
offset_ns: int32
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [], "columns": [{"name":' + 734
--------------------
0: name=x, type=halffloat
1: name=y, type=halffloat
2: name=z, type=halffloat
3: name=intensity, type=uint8
4: name=laser_number, type=uint8
5: name=offset_ns, type=int32


In [24]:
import pyarrow.feather as feather

table = feather.read_table(
    "/data/charlie/BagMonster/Dataset/bag_cache/rosbag2_2025_05_21-18_55_10_0/sensors/lidar/1747824910799631196.feather"
)
print(table.num_rows, "rows")
print(table.schema)

23694 rows
x: halffloat
y: halffloat
z: halffloat
intensity: halffloat


In [54]:
import pandas as pd
table = pd.read_feather(
    "/data/charlie/BagMonster/Dataset/bag_cache/rosbag2_2025_05_21-18_55_10_0/city_SE3_egovehicle.feather"
)
print(len(table["timestamp_ns"].values))
table[0:5]

750


timestamp_ns        qw        qx        qy        qz      tx_m  \
0  1747824910799631196 -0.933707 -0.357997 -0.004208 -0.003419  7.362783   
1  1747824910859147739 -0.933692 -0.358036 -0.004198 -0.003352  7.362732   
2  1747824910959389211 -0.933697 -0.358027 -0.004071 -0.003313  7.362696   
3  1747824911059436324 -0.933698 -0.358023 -0.004080 -0.003347  7.362665   
4  1747824911159485891 -0.933690 -0.358044 -0.004054 -0.003337  7.362635   

        ty_m        tz_m  
0 -14.446256  138.304825  
1 -14.446217  138.305679  
2 -14.446192  138.308823  
3 -14.446167  138.307632  
4 -14.446135  138.305954